version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
      APP_CLIENT_ORIGIN: http://localhost:3000
    command: >-
      sh -c "[ -f .env ] || cp .env.example .env && \
      composer install && \
      php artisan key:generate --force && \
      php artisan migrate --force && \
      php -S 0.0.0.0:8000 -t public public/index.php"
    ports:
      - "8000:8000"

  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      - API_ORIGIN=http://localhost:8000
    command: sh -c "npm install && npm run watch & npm start"
    ports:
      - "3000:3000"
