version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_CLIENT_ORIGIN: ${APP_CLIENT_ORIGIN}
    command: >-
      sh -c "[ -f .env ] || cp .env.example .env && \
      composer install && \
      php artisan key:generate --force && \
      php artisan migrate --force && \
      php -S 0.0.0.0:8000 -t public public/index.php"
    ports:
      - "8000:8000"

  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      - API_ORIGIN=${API_ORIGIN}
    command: sh -c "npm install && npm run watch & npm start"
    ports:
      - "3000:3000"
